.gitignore
neovim/__init__.py
neovim/api/nvim.py
neovim/msgpack_rpc/event_loop/base.py
neovim/ui/__init__.py
neovim/ui/cli.py
neovim/ui/gtk_ui.py
neovim/ui/screen.py
neovim/ui/tickit_ui.py
neovim/ui/ui_bridge.py
setup.py

Prototyping a graphical and text UI for helping me fix issues with the abstract ui code. This branch depends on neovim/neovim#1657.

[RDY] UI prototypes

---

neovim/api/common.py
test/test_buffer.py

I'm no rocket scientist but this seems to fix #98 for me. Neovim is working
very smoothly for me now. Thanks!

Fix RemoteSequence.__contains__

---

setup.py

[RFC] setup.py: Add optional GUI dependencies.

---

.travis.yml
test/test_buffer.py
test/test_vim.py

Test failures from changes in neovim upstream. the test now documents the correct behaviour as fixed in neovim/neovim#3315

[RFC] tests: Update tests to neovim changes

---

neovim/msgpack_rpc/event_loop/asyncio.py

updated _connect socket function and tests to work with windows.
fixes #157

attach to neovim on windows

---

neovim/api/buffer.py
neovim/api/nvim.py

buffer: add wrappers for add_highlight/clear_highlight functions

---

MANIFEST.in

Add README.md & LICENSE to source distribution

---

neovim/plugin/host.py
neovim/plugin/script_host.py

Some people seem to have trouble with host finding the script host. Let's just use ordinary imports for this.

host: more robust way of finding the script host

---

neovim/api/nvim.py
neovim/plugin/host.py
neovim/plugin/script_host.py
neovim/util.py

plugin host: hide irrelevant parts of request tracebacks

---

neovim/api/buffer.py
neovim/plugin/script_host.py

update to new get_lines/set_lines API

---

neovim/plugin/decorators.py

typo: s/the a class/the class/

---

neovim/plugin/script_host.py

Later on we should make the existing code safe, see https://github.com/neovim/python-client/issues/337#issuecomment-385608627
Quick fix for the bug in 0.2.5 for now.

script_host: avoid race in initialization. fixes #337

---

neovim/api/nvim.py
neovim/msgpack_rpc/event_loop/__init__.py
neovim/msgpack_rpc/event_loop/asyncio.py
setup.py

Note: doesn't work yet. I will setup the windows WM tomorrow.
Also, getting appveyor on this repo might be a good idea.

Enable asyncio on window again

---

setup.cfg

Ignore W504 (using W503):
> W504 line break after binary operator

Fix flake8 config

---

.scrutinizer.yml
.travis.yml

Closes https://github.com/neovim/python-client/pull/356.

Travis: test with Python 3.7

---

pynvim/msgpack_rpc/event_loop/asyncio.py

Fixes #60 and https://github.com/neovim/neovim/issues/9397.
Or at least it avoids the crash. We should also make the stderr visible i e when `UpdateRemotePlugins`, but that is nvim core issue. (technically each rplugin host could do it using an internal pipe, but we can just as well have a one-size-fits-all solution in nvim core).

rename stdout fd in stdio mode

---

setup.cfg
setup.py

Done following the instructions from: https://pypi.org/project/pytest-runner
Fixes https://github.com/neovim/pynvim/issues/394

Make `setup.py test` use pytest

---

pynvim/api/nvim.py
pynvim/msgpack_rpc/__init__.py
pynvim/msgpack_rpc/async_session.py
pynvim/msgpack_rpc/session.py
pynvim/plugin/host.py
pynvim/util.py
test/test_host.py
test/test_vim.py

Set basic client info for all connections, not only host.

session: set client info

---

MANIFEST.in

Fixes https://github.com/neovim/pynvim/issues/367

Add test/conftest.py to PyPI sdist

---

.travis.yml

ci: Travis: pip-install is not required

---

.codecov.yml
.coveragerc
.travis.yml
tox.ini

Add "cov" tox factor, which should get used by tox-travis then.

ci: fix coverage reporting

---

pynvim/api/nvim.py
test/test_vim.py

Taken out of https://github.com/neovim/pynvim/pull/405.

errors: decode bytes

---

pynvim/api/common.py
pynvim/api/nvim.py
setup.cfg
test/conftest.py
test/test_buffer.py
test/test_tabpage.py
test/test_vim.py
test/test_window.py

Fixes https://github.com/neovim/pynvim/issues/402
TODO:

[RDY] Add support for proper deletion, raising KeyError where appropriate

---

pynvim/plugin/host.py
test/conftest.py
test/test_events.py
test/test_host.py
test/test_vim.py

host: set self.name for _on_error_event

---

README.md

doc: release

---

pynvim/plugin/host.py

Since there are no reasonable alternatives to imp in python2.7,
I figured it'd be the easiest to try importing python3 modules and if
that fails, fall back to the previous method. However this will remove
that annoying DeprecationWarning for everyone using python3.

Refactor: Remove usage of imp

---

pynvim/compat.py
pynvim/plugin/script_host.py

Rebase of https://github.com/neovim/pynvim/pull/486

avoid imp module

---

.github/workflows/test.yml
docs/conf.py
pynvim/__init__.py
pynvim/api/buffer.py
pynvim/api/common.py
pynvim/api/nvim.py
pynvim/compat.py
pynvim/msgpack_rpc/event_loop/asyncio.py
pynvim/msgpack_rpc/session.py
pynvim/plugin/decorators.py
pynvim/plugin/host.py
pynvim/util.py
setup.cfg
tox.ini

Example run: https://github.com/jamessan/pynvim/actions/runs/382403759

Add GitHub actions CI

---

.readthedocs.yml
setup.py
tox.ini

ci: fix failing readthedocs build
