- neovim/api/nvim.py
- fchdir is not portable to Windows, trying to import it caused
an error
- issue #81
> Remove use of os.fchdir

- neovim/plugin/decorators.py
- neovim/plugin/host.py
- Partial fix for neovim/neovim#1829
- I'm a bit at lost as to why the functools.partial is being used here, It
clearly does not work for Python3, but it is not clear to me what is it
supposed to be doing @tarruda?
- Encoding names in Python3 need to be strings, fixes Host._nvim_encoding
- Binary strings from msgpack are decoded as the bytes type, but rpc method
names used by rpc_export are unicode strings, this causes a comparison
between the request names and the exported functions to fail (use &encoding
to decode)
> Python3 fixes: functools.partial and encoding

- neovim/msgpack_rpc/session.py
While NVIM_PYTHON_LOG_FILE can be used to retrieve these, it seems to be
more convenient to know where an error is coming from.
Maybe only `format_exc` should be used.  Please feel free to adopt it as needed.
> Provide exception traceback in error response

- setup.py
The experimental GUI does not work with Python 3; disable it.
Closes #114.
> [RFC] Disable GUI for Python 3.

- neovim/api/common.py
- neovim/plugin/decorators.py
- neovim/plugin/host.py
In a python3 rplugin, per default, return values from api functions like `nvim.eval()` will return unicode strings while args to rpc functions (`@neovim.function` etc)  will be passed as bytes, which is inconsistent and surprising. This PR fixes so that args to rpc functions will be decoded the same way, and this can be overidden by `@neovim.encoding` dectorator on the plugin (or individual method) the same way. No change of defaults for python2, where behaviour already is consistent.
ping @shougo @razvanc87 and others developing python3 plugins.
> handle decoding for rplugin methods the same as for api calls

- neovim/api/common.py
- neovim/api/nvim.py
- neovim/msgpack_rpc/async_session.py
- neovim/msgpack_rpc/session.py
- test/test_client_rpc.py
- test/test_events.py
Allows to call neovim rpc methods asynchronously. This is useful to be able to make a lot of calls without requiring 2 context switches per call. For instance for `bufhl` a rich highlighter might make thousands of `buffer_add_highlight` at once for a big file.
Not sure of the api though, perhaps `vim.session.request(..., async=True)` is better?
> [RFC] allow async method calls to nvim

- neovim/api/nvim.py
- test/test_client_rpc.py
- test/test_vim.py
This exposes a method call syntax for calling vimscript functions
nvim.viml.MyVimscriptFunction(args)
Not sure `viml` is the best name. And what happens if we support async calls, would it be `nvim.viml_async.Func(...)` or `nvim.viml.Func(..., async=True)`. ?
> [RFC] expose vim_call_function

- neovim/api/nvim.py
- neovim/msgpack_rpc/msgpack_stream.py
This is defined to be `utf-8` per msgpack spec and was already the default in `msgpack.Packer`.
Might fix neovim/neovim#3618
> [RFC] Don't override the encoding of msgpack STRings

- setup.cfg
Alternatively we could change the code, but I think the code looks good as it is.
> lint: ignore E731 "do not assign a lambda expression"

- neovim/msgpack_rpc/event_loop/asyncio.py
This patch helps show the underlying error in [#152](https://github.com/neovim/python-client/issues/152)
BaseException.message was only available in Python 2.5:
https://www.python.org/dev/peps/pep-0352/#retracted-ideas
This was patch was proposed in neovim/neovim #4253 by @equalsraf :
https://github.com/neovim/neovim/issues/4253#issuecomment-184437483
Without the change calling BaseException.message hides any errors behind an AttributeError:
AttributeError: 'OSError' object has no attribute 'message'
> Don't use BaseException.message @equalsraf #152

- neovim/__init__.py
- neovim/api/nvim.py
- neovim/msgpack_rpc/session.py
- neovim/plugin/host.py
- test/test_common.py
- test/test_concurrency.py
This oneliner crashes the python client:
`py vim.session.threadsafe_call(lambda: [vim.eval("3"),undefined_variable])`
yes the `vim.eval("3")` is needed.
Print exceptions arising from async plugin handler, as already is done for sync ones.
Define `nvim.threadsafe_call` a wrapper around `nvim.session.threadsafe_call`) that prints uncaught exceptions in the async call, as well as the context the call came from. Also I don't think we should recommend plugins to call methods on `nvim.session` if they can avoid it, it's better to put all exported methods, including `threadsafe_call` on the api objects.
Docs are missing, so WIP.
> better handling of exceptions in async contexts

- neovim/plugin/host.py
- neovim/plugin/script_host.py
- setup.cfg
I just realized we can mitigate the version incompatibility issue. This version of the python-client is compatible with neovim both before and after neovim/neovim#4418. So what we should do is:
* merge this and release python-client 0.1.4
* wait a bit
* merge neovim/neovim#4418
* wait a bit
* merge the rest of #179
> Script host

- neovim/__init__.py
- neovim/plugin/host.py
Currently when having a package in `rplugin/python3`:
~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/
one needs to have a empty marker file
~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete.py
This patch removes that need. It also has a workaround to support the existing workaround, which should be removed eventually.
Needs an update to neovim/neovim as well
> Make the host find package dirs in "rplugin/python3"

- neovim/__init__.py
- neovim/msgpack_rpc/__init__.py
- neovim/msgpack_rpc/session.py
- neovim/plugin/host.py
On `:UpdateRemotePlugins`: if a plugin fails to load due to import error, tell the user/developer about it.
If a request handler is missing due to import error (the plugin file or dependency thereof was changed since the last URP) give the import error instead of useless traceback of the host/msgpack implementation (or even worse: no error at all for async notifications)
> be more verbose about import errors

- neovim/api/buffer.py
To preserve compatibility with Vim, the end of the range should point
at the last line of the range, not at the first line below.
The inconsistency can be demostrated by running (both in Vim and Neovim):
:python import vim; print vim.current.range.start, vim.current.range.end
either with visual range selected or without it.
Fixes #185.
> Range: The end of the range should point at the last line of the range

- neovim/__init__.py
- neovim/api/__init__.py
- neovim/api/common.py
- neovim/api/nvim.py
- neovim/msgpack_rpc/session.py
- neovim/plugin/__init__.py
- neovim/plugin/decorators.py
- neovim/plugin/host.py
- test/test_common.py
While doing breaking changes ( #179 ) ...
Per decision, rplugins do not need support `encoding != utf-8`. (But it should not be too hard to add back if we really want this.) But setting the encoding (and not just an on/off switch) per rplugin definitely makes no sense.
Allows to turn on/off decoding per request, ref #184 .
> remove decodehook

- neovim/plugin/decorators.py
Defining a command with `bang=True` leads to a .init.vim-rplugin~ file which Neovim can't read.
I'm not sure if this belongs here or if it is a Neovim bug, but it's quite easy to fix.
> Fix `bang` and `register` command modifier

- neovim/api/common.py
- neovim/compat.py
- neovim/msgpack_rpc/msgpack_stream.py
- neovim/plugin/decorators.py
- test/test_buffer.py
```
0put =printf('%c',0xFF)
py3 print(repr(vim.current.buffer[0]))
py3 vim.current.buffer[0] += "x"
```
the first one is ok in vim, but not the second. This makes both possible in neovim.
fixes #198
> change default unicode error mode to "surrogateescape"

- setup.py
> [WIP] Use pyuv on Windows

- README.md
- neovim/api/buffer.py
- neovim/api/common.py
- neovim/api/nvim.py
- test/test_vim.py
`python-buffers` describes `vim.buffers` as a mapping object. `python-buffer`
documents that `b.number` where `b` is a Buffer object can be used as a
`python-buffers` key. I.e. `b == vim.buffers[b.number]` should be true if `b`
is a valid buffer object.
`nvim.py` was implementing `vim.buffers` as a `RemoteSequence` which doesn't
provide the aforementioned properties. This change implements it as a
`RemoteSequenceAsMap` object instead. The latter is a new class that
allows a sequence returned via a single msgpack-rpc call to be exposed
to Python as a map.
> vim.buffers is a map not a list.

- neovim/api/buffer.py
- neovim/api/nvim.py
- neovim/plugin/host.py
fixes #216. A modified test case to cover both cases:
```
import sys
import os
from neovim import attach
def setup_cb():
nvim.command('call rpcnotify({}, "foo")'.format(nvim.channel_id))
nvim.call('rpcrequest', nvim.channel_id, "bar", "xx", async=True)
def notification_cb(msg, _args):
num -= 1
def request_cb(name, args):
FAIL
nvim = attach('child', argv=['nvim', '-u', 'NONE', '--embed'])
nvim.run_loop(request_cb, notification_cb, setup_cb)
```
This should not affect plugins running inside vim, as the plugin host already catches `Exception`:s and displays the plugin traceback appropriately.
> nvim: show errors in handler on stderr when used as client

- neovim/msgpack_rpc/event_loop/asyncio.py
sys.stderr might be monkey-patched by other library like kivy (ref #218)  and not always
work. Also it gives the impression the stderr stream of the python process
is used which it isn't.
> asyncio: use stderr fd constant

- README.md
- neovim/__init__.py
- test/test_common.py
Fixes #222 . Logs now have names as `{$NVIM_PYTHON_LOG_FILE}_py{X}_{NAME}` where X is 2 or 3 and NAME is either "rplugin" or "script" (or "test" when running nosetests with logging). ping @blueyed
> logging: use predictable log file names

- neovim/api/tabpage.py
- neovim/api/window.py
- test/test_tabpage.py
- test/test_window.py
The legacy if_pyth interface exposed a number attribute which was
equivalent to the winnr() and tabpagenr() values for the window and
tabpage, respectively.
Neovim 0.1.6 added the necessary API functions to support exposing this
information.
Closes #87
> Add number attribute to Window and Tabpage objects

- neovim/__init__.py
- neovim/api/buffer.py
- neovim/api/nvim.py
- neovim/api/tabpage.py
- neovim/api/window.py
- neovim/util.py
- setup.py
- test/test_buffer.py
Citing the nvim help:
> The Python client is the reference implementation for API clients. It is
always up-to-date with the Nvim API, so its source code and test suite are
authoritative references.
As the tests show, this is a slightly _breaking_ change for `obj.api.method(...)`. We could mitigate that by letting the `RemoteApi` contain a whitelist of deprecated and renamed methods, but I doubt that it would affect any plugin as all the functionality of the deprecated and renamed methods are more conveniently exposed through the standard (hard-coded) python interface.
> [RFC] update to api level 1

- neovim/api/buffer.py
- neovim/api/common.py
- test/test_window.py
In conversion with @justinmk (on gitter), we decided to "freeze" the current msgpack EXT representation objects, which simply is the handle (buffer number, window id) of the object. This means `nvim_buf_get_number` is very unneccesery, it takes the (doubly-encoded) number and just echoes the same number back, single-encoded.
This makes `buffer.number` deduce the number from the `code_data`, instead of using a blocking rpc call. This means it can be safely used in async handlers and threads, for instance buffer change notifications (neovim/neovim#5269) will send a buffer object in async notifications, but one might want to use the number for bookkeeping etc.
This also exposes Object.handle, I think it is very unlikely that vim will introduce something conflicting here, if anythink they …
> api: export Object.handle and make Buffer.number non-blocking

- neovim/msgpack_rpc/event_loop/asyncio.py
Fix problems reported in #238 for Python3.6. ( In python3.5 I couldn't reproduce the error)
Tested with python versions: 2.7.13, 3.4.5, 3.5.2 and 3.6.0.
In python 3.4, and 3.5, we have this:
```
Exception ignored in: <bound method _UnixSelectorEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
File "/home/meiralins/.pyenv/versions/3.4.5/lib/python3.4/asyncio/base_events.py", line 417, in __del__
File "/home/meiralins/.pyenv/versions/3.4.5/lib/python3.4/asyncio/unix_events.py", line 58, in close
File "/home/meiralins/.pyenv/versions/3.4.5/lib/python3.4/asyncio/unix_events.py", line 139, in remove_signal_handler
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
Exception ignored in: …
```
> Attach child handler loop.

- neovim/msgpack_rpc/event_loop/uv.py
- setup.py
This solves issue #88.
According to the pyuv [releases](https://github.com/saghul/pyuv/releases) the API changed in version 1.0.0 in Dec 2, 2014.
> Fix #88: conform to 'new' pyuv API

- test/test_vim.py
Test "test_vim.test_command" was failing because of the call to
os.unlink(..), as the file was still open in vim. Adding a conditional
to execute the call only if we are not running under Windows was the
most straight-forward "fix".
Test "test_vim.test_chdir" was failing for two reasons. Firstly because
of missing Windows-specific handling of path names in
find_file_in_path_option in file_search.c in Neovim core. Secondly
because although one can indeed `:cd /` on Windows (or at least, should
be able to), a corresponding call to `:pwd` will echo the root drive
of the current working directory of Neovim.
test_chdir should work now that neovim/neovim#4711 was merged.
> Fix failing tests on Windows.

- setup.cfg
Travis-CI-Build currently fails on the codebase of `python-client` in general for all PRs (except this one fixing the issue), because D401 of `flake8` complains about D401 at certain positions.
This adds D401 to the ignore-list in `setup.cfg` to avoid this.
> Ignore D401-type-complaints of flake8

- neovim/api/buffer.py
- test/test_buffer.py
This commit fixes a bug in Range, leading to the last line of a Range
not being able to be replaced via `__setitem__` as the final
line setting its contents in the buffer the Range is based on assumes the
end-index to be inclusive, which it isn't in Python-slicing-notation.
@justinmk
> Raise end-index by 1 when setting parts of Range

- neovim/__init__.py
https://github.com/roxma/nvim-completion-manager/issues/148#issuecomment-337771822
To avoid error on systems with non unicode compatible encoding returned by `locale.getpreferredencoding()`
> always use utf-8 encoding instead of locale.getpreferredencoding()

- README.md
- neovim/__init__.py
- neovim/api/nvim.py
- neovim/msgpack_rpc/session.py
- neovim/plugin/decorators.py
- neovim/plugin/host.py
> rplugin: conditionally enable nested notifications

- setup.py
The official package was renamed to `msgpack` whereas `msgpack-python` still acts as a transition package for it.
Relevant commits:
- https://github.com/msgpack/msgpack-python/commit/89e4f8b7b3a43fc84ea0dd278a4b8b54b1fac4bd
- https://github.com/msgpack/msgpack-python/commit/9f4c12f29ce7a6d62423311ab12a031dc79c458a
- https://github.com/msgpack/msgpack-python/commit/5be93786404d4e95de933d1bc64640402c3f2696
> Setup: don't use transition package as dependency

- neovim/msgpack_rpc/msgpack_stream.py
temporary fix for msgpack-python 0.5.2
fixes #299
> msgpack: specify encoding togheter with unicode_errors

- neovim/plugin/decorators.py
- test/test_decorators.py
The command decorator was only checking the truthyness of `count`, which
meant that a value of 0 was considered falsy and so the value not passed
to the decorated function. A value of 0 for `count` should be valid
since this is the default in both vim and neovim (see `help v:count`).
> Check count for 'not None' instead of truthy in command decorator

- neovim/__init__.py
- neovim/api/nvim.py
- neovim/msgpack_rpc/async_session.py
- neovim/msgpack_rpc/event_loop/asyncio.py
- neovim/msgpack_rpc/event_loop/base.py
- neovim/msgpack_rpc/event_loop/uv.py
- neovim/msgpack_rpc/msgpack_stream.py
- neovim/msgpack_rpc/session.py
work on #264. Handles the failure case for now. cc @mhinz
> [WIP] closing the event loop

- .travis.yml
- README.md
- neovim/api/nvim.py
- neovim/msgpack_rpc/async_session.py
- neovim/msgpack_rpc/event_loop/__init__.py
- neovim/msgpack_rpc/msgpack_stream.py
- neovim/msgpack_rpc/session.py
- setup.py
Currently, handling events beyond nvim itself is very limited, the only way additional sources can be added is with separate threads invoking `nvim.async_call`.  A problem is that the implemenation is dynamic between two event loops: asyncio and pyuv, so plugins can't use them.
The plan is to require asyncio on python3 so we can expose asyncio event loop to python3 rplugins. Python3.3 is hereby unsupported. Python2.7 rplugins is considered legacy: existing py2.7 rplugins remain supported for now, but new features might not be available (python2 via vim `:python` interface remain supported of course)
I know issues on windows has held up this change in the past (#243). We might need to change the asyncio backend on windows. IIRC there is even a libuv based backend, but I don't know it's …
> [WIP] Expose asyncio to python3 rplugins, removing python3.3 support

- neovim/api/nvim.py
- neovim/msgpack_rpc/event_loop/__init__.py
- setup.py
Disable asyncio on windows for now. `nvim.loop` will only be available on POSIX until stdio is fixed (hopefully soon).
> event loop: disable asyncio on windows for now

- neovim/api/common.py
This is a trivial fix. 
I use new API names instead of deprecated ones in pydoc of RemoteSequence.
Ref: https://github.com/neovim/neovim/blob/master/src/nvim/api/dispatch_deprecated.lua
best regards.
> Fix deprecated API names in pydoc.

- neovim/api/common.py
I found several dead code in neovim/api/common.py. This PR removes them.
Best regards.
> Remove dead code.

- test/test_vim.py
1. The `with_setup` decorator does not appear to be designed to be used
without parenthesis.  Remove it, since it is not needed/used anyway.
2. Fix the actual test.
> tests: fix test_command_output

- docs/installation.rst
- neovim/plugin/script_host.py
- test/test_vim.py
This is implementing #295 and https://github.com/neovim/neovim/issues/3636.
> Correctly change the working directory in python

- neovim/api/buffer.py
- neovim/api/nvim.py
- neovim/compat.py
- test/test_buffer.py
- test/test_vim.py
Async rplugins (and sync ones for that matter) should conveniently be able to use lua to execute some logic on the nvim side. Rplugins can use `exec_lua(""" ....  _myplugin = {...}""")` or `exec_lua('_myplugin = require("myplugin")')` to define a module with helper functions, and then use `nvim.lua._myplugin.myfunction(..., [async=True])`  to call it.
The `update_highlights` shows an example of the helper function pattern. Though it gets a bit more complex  as we expect multiple copies of the python host, ordinary rplugins need not add the channel_id to the module name like the host does. nvim-ipy will add a more simple example how this can look for an rplugin.
> Add lua integration (and update_highlights as an useful example)

- neovim/plugin/script_host.py
This fix is related to https://github.com/neovim/python-client/pull/274.
On my environment(OSX 10.12.6), Syntax error occurs when python-client is imported on Python 3.7.
Reproduced steps are here.
```
$ ~/repos/cpython/py3.7/beta/bin/python3 --version
Python 3.7.0b3+
$ ~/repos/cpython/py3.7/beta/bin/pip3 install -U .
$ ~/repos/cpython/py3.7/beta/bin/python3 -c 'import neovim'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/tatsuro/repos/python-client/neovim/__init__.py", line 13, in <module>
from .plugin import (Host, autocmd, command, decode, encoding, function,
File "/Users/tatsuro/repos/python-client/neovim/plugin/__init__.py", line 5, in <module>
from .host import Host
File "/Users/tatsuro/repos/python-client/neovim/plugin/host.py", line 11, in …
```
> Fix syntax error when python-client is imported on Python 3.7.

- README.md
- docs/development.rst
- docs/usage/python-plugin-api.rst
- docs/usage/remote-plugins.rst
Clean up README.md and use references to readthedocs. 
Start to use "pynvim" name more often in the docs. I will do a functional release first with py3.7 and lua support (0.2.5).  After that a separate release that _only_ does the formal rename, including updating the installation commands in the docs (0.2.6 or 0.3).
> docs for the next release (0.2.5)

- neovim/plugin/script_host.py
The fix is similar to what VimModuleLoader.find_module does already.
> Fix VimPathFinder.find_spec (Python 3.4+)

- neovim/api/nvim.py
`ui_attach` and `ui_detach` are deprecated.
This handles the old signature, and issues a DeprecationWarning itself
then.
> Use nvim_ui_attach/nvim_ui_detach

- neovim/msgpack_rpc/msgpack_stream.py
- setup.cfg
Fixes:
…/neovim-python-client/neovim/msgpack_rpc/msgpack_stream.py:24: PendingDeprecationWarning: encoding is deprecated.
unicode_errors=unicode_errors_default)
Also configures pytest to display these warnings.
> Fix PendingDeprecationWarning with Packer.encoding

- pynvim/api/common.py
- pynvim/api/nvim.py
- pynvim/msgpack_rpc/session.py
- pynvim/plugin/host.py
- pynvim/plugin/script_host.py
- setup.cfg
Converse of #361: Ignore W503 and enforce W504.
This matches the style of Nvim core and is just better :)
> lint: Enforce "line break before operator"

- pynvim/compat.py
- pynvim/plugin/script_host.py
closes #368
regresses #351
There is more involved with migrating to `find_spec()` and Python's new
enterprise-quality API.  We may not be able to fashion a compat wrapper
that mimics the old find_module() API.
- `find_spec()` returns `importlib.machinery.ModuleSpec` object, unlike
`find_module()` which returns 3 values.
- `host.py` sends the result to `imp.load_module()` ...
Reverts the following:
8df286143cce
a29f34e98e2b
e29e4dfee094
> Revert: fix "imp" module deprecation warnings

- pynvim/util.py
Each item will already end in an newline. This will make a difference when we start to use multiline exceptions in Nvim core (https://github.com/neovim/neovim/pull/7969)
> util: don't add extra newlines in format_exc_skip

- pynvim/api/nvim.py
Just like to the correction about linefeeds made in the last commit, `err_write` doesn't buffer input but the docs don't mention it.
> err_write docs

- test/test_vim.py
While `'listchars'` is a global option in Nvim 0.3.5, in HEAD it was changed to be local to the window.
> tests: global and local options

- pynvim/api/buffer.py
- test/test_buffer.py
Adding __ne__ function to pynvim.api.buffer.Buffer to correctly test
two buffers are not equal in Python 2. Test added to demonstrate.
Also fixing warning message in test_buffer:96
> Fixing issue #398: `buf1 != buf2` doesn't work in python2

- tox.ini
This uses `extras_require` from `setup.py` (a central place to define
requirements for testing).
Removes "pytest-xdist", which is not used currently (and not necessary
given that tests are fast).
> tox: use extras=test

- test/conftest.py
- test/test_buffer.py
- test/test_tabpage.py
- test/test_vim.py
- test/test_window.py
The "vim" fixture uses a new session always.
It was added when migrating to pytest in b65f62d, but is not really
necessary.  It could still be used to e.g. ensure tests are cleaning up
after themselves, but this is also not necessary really.
Adjusts existing tests, mainly with regard to handle IDs.
> tests: remove cleanup_func

- docs/usage/remote-plugins.rst
- pynvim/plugin/host.py
Also if plugin A is invoked, don't construct plugin B until any of B:s
methods is invoked.
Seemst to fix #362 in my quick testing. Also if a plugin does crazy stuff in `__init__` it will not affect URP or when another plugin is started. Still I think explicit plugin start method is a better pattern.
> host: do not construct plugin objects on UpdateRemotePlugins

- setup.py
pytest runner should not be unconditionally included in setup_requires
This change makes it conditional on setup.py invocation arguments as recommended upstream [1]
See: https://github.com/pytest-dev/pytest/issues/3814
Identified via: [FreeBSD Ports Bug 242065](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242065)
Closes #417
Closes #420
[1] https://pytest-runner.readthedocs.io/en/latest/#conditional-requirement
> Make pytest-runner conditional

- pynvim/plugin/script_host.py
- test/test_host.py
> imports vim module by default.

- pynvim/compat.py
- pynvim/msgpack_rpc/msgpack_stream.py
- test/test_buffer.py
> Set unicode_errors in Unpacker

- pynvim/__init__.py
- pynvim/api/__init__.py
- pynvim/api/buffer.py
- pynvim/api/common.py
- pynvim/api/nvim.py
- pynvim/api/tabpage.py
- pynvim/api/window.py
- pynvim/msgpack_rpc/__init__.py
- pynvim/msgpack_rpc/event_loop/__init__.py
- pynvim/msgpack_rpc/event_loop/asyncio.py
- pynvim/msgpack_rpc/event_loop/uv.py
- pynvim/msgpack_rpc/msgpack_stream.py
- pynvim/msgpack_rpc/session.py
- pynvim/plugin/__init__.py
- pynvim/plugin/decorators.py
- pynvim/plugin/host.py
- pynvim/plugin/script_host.py
@Shougo I realized that going ahead and changing all the imports wouldn't be very time intensive so I did.
In addition, I have verified that tests still pass with pytest in a venv.
However, I would like to note that:
`python -m doctest pynvim/msgpack_rpc/event_loop/base.py`
currently fails. There's a circular import issue, and even if that was resolved, it seems that Tracebacks were copy-pasted into `BaseEventLoop.__init__()`.
However that may be an issue for a different PR, and the imports mentioned in #450 are fixed
> Close #450: Modify all imports in the repository to absolute imports

- docs/usage/python-plugin-api.rst
- docs/usage/remote-plugins.rst
Building the docs raised errors for me because the lines under the headers were too short.
In addition, a few of the code blocks weren't being properly highlighted (I.E. the bottom of <https://pynvim.readthedocs.io/en/latest/usage/remote-plugins.html> ) so I changed the lexer to signify that the code blocks are run inside of Vim and fixed the indentation and that seems to have worked for me.
> Doc updates: Indentation and underline length

- pynvim/plugin/script_host.py
Replace imp.new_module with types.ModuleType which is available from
py2.7 to 3+
> Reduce usage of deprecated imp module

- docs/usage/python-plugin-api.rst
- pynvim/__init__.py
- pynvim/api/buffer.py
- pynvim/msgpack_rpc/async_session.py
- scripts/logging_statement_modifier.py
- test/test_decorators.py
There are small typos in:
- docs/usage/python-plugin-api.rst
- pynvim/__init__.py
- pynvim/api/buffer.py
- pynvim/msgpack_rpc/async_session.py
- scripts/logging_statement_modifier.py
- test/test_decorators.py
Closes #487
> docs: fix a few simple typos

- pynvim/plugin/script_host.py
- test/test_host.py
This PR fixes an issue that when calling `vim.eval('v:true')`, or `vim.eval('v:false')`, it gives the wrong `str` type.
In the latest version of `vim`, when executing below Ex command, the result is `<class 'bool'>`. But in `neovim`, it is `<class 'str'>`.
```
:py3 print(type(vim.eval('v:true')))
```
> Fix: evaluate v:true/v:false to python bool type

- .gitignore
- README.md
- pynvim/util.py
- pyproject.toml
- setup.py
Hi all.  These changes are in response to issue #518 and bring the package to minimal compliance with packaging standards so we don't get deprecation warnings from pip due to outdated packaging format.  Highlights:
- Changed packaging and uploading commands in REAME to allow for building and uploading a source distribution as well as a wheel.
- Added language to setup.py to create universal wheel (necessary for continuing py2.7 compatibility - even if py2.7 is EOL).
- Add minimal pyproject.toml file to meet standards.
This is my first PR, so if I missed something please let me know!
> Packaging update

- test/test_buffer.py
`test_options` has an assertion that tests whether setting a local value modifies the global value, but tests it against a hardcoded constant.
This constant changed in https://github.com/neovim/neovim/commit/fcfe535e9877cfdc824dc78f2d19e590400d34cd
and
https://github.com/neovim/pynvim/commit/82a2e14b96fbffa30caeefec6e86b668c96662eb fixes it by using the new constant instead, but this causes tests to fail against even the latest released version of neovim.
To make this version-agnostic, save the old global value, and assert that the new value is equal after setting the local value.
> test_buffer: don't depend on version-dependent default values of 'define'

- setup.cfg
This option is no longer valid with pytest 6+
```
========================================================= warnings summary =========================================================
.venv311/lib64/python3.11/site-packages/_pytest/config/__init__.py:1373
/home/michel/src/github/neovim/pynvim/.venv311/lib64/python3.11/site-packages/_pytest/config/__init__.py:1373: PytestConfigWarning: Unknown config option: timeout
self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
See e.g. https://github.com/samuelcolvin/rtoml/issues/12
> Fix `Unknown config option: timout` warning

- pynvim/plugin/host.py
- test/fixtures/module_plugin/rplugin/python3/mymodule/__init__.py
- test/fixtures/module_plugin/rplugin/python3/mymodule/plugin.py
- test/fixtures/simple_plugin/rplugin/python3/simple_nvim.py
- test/test_host.py
The removal of `imp` package (#461) in order to supprot Python 3.12 had a bug where rplugins can't be loaded and the ImportError exception was silenced, making the remote provider throwing lots of errors. This commit fixes broken dynamic import of python modules from the registered rplugins.
We add tests for Host._load, with loading rplugins consisting of:
(1) single-file module  (e.g., `rplugins/simple_plugin.py`)
(2) package (e.g., `rplugins/mymodule/__init__.py`)
Note: As per https://docs.python.org/3.12/whatsnew/3.12.html#imp, I also tried something like:
```python
def _handle_import(path, name):
spec = importlib.machinery.PathFinder.find_spec(name, [path])
if spec is None:
filename = os.path.join(path, name + '.py')
loader = importlib.machinery.SourceFileLoader(name, filename)
spec = …
```
> fix: fix broken dynamic import of rplugin modules

- .github/workflows/test.yml
- setup.py
- test/conftest.py
- test/test_vim.py
neovim's python3 provider detection has a bug on python3.12
(neovim/neovim#25316), so we work around this by explicitly setting
the `g:python3_host_prog` variable.
Also, pynvim on python3.12 requires greenlet 3.x.
Fixes #528
> ci: Add python3.12 support

- .github/workflows/test.yml
- README.md
- docs/development.rst
- setup.py
- test/conftest.py
- tox.ini
- Include python 3.7, 3.8, and 3.9 as well to the Github CI actions.
- Configure tox to run tests on python3.7-python3.12 (skip if python
interpreters are not found on local environments).
- Add "Contributing" section to docs/development, suggesting how to run
tests locally.
- Unify the way how we specify pytest options (`-s -vv`) into tox.ini.
- Bump up `python_requires` to 3.7 in the package spec.
- Make sure to use `nvim --clean` to against flaky tests. No SHADA and
swapfiles should be used.
> ci: Run CI and tox test for all supported python versions 3.7+

- setup.py
Greenlet 3.0 has been released including full python 3.12 support. It
also works well with older python versions, so we can now have the
dependency `greenlet >= 3.0`.
> chore: use greenlet >= 3.0

- .github/workflows/test.yml
- pynvim/msgpack_rpc/event_loop/asyncio.py
- test/conftest.py
- test/test_host.py
- test/test_vim.py
- tox.ini
🎉✅ *TESTS on WINDOWS ARE NOW ALL GREEN* ✅🎉
Note: This PR consists of several commits and bugfixes, each of which is all required to fix the broken tests on windows platform for such a long time. I would like to request @justinmk that please merge this PR **without squashing** (either merge commit or rebasing), retaining all the individual commits.
Most importantly, this PR should fix #505. Pipe (subprocess) based pynvim was broken since neovim 0.5.0, probably due to https://github.com/neovim/neovim/commit/c86d5fa981b0651167f789aaff685b42cad7aaca (neovim/neovim#11390): on Windows, stderr is closed for an embedded nvim.
See the commit message for more details.
See the commit message for more details. asyncio event loops were not closing properly during tests, and were leaking in subsequent …
> Fix broken tests on Windows due to EOF error and other minor bugs

- README.md
- pynvim/__init__.py
- pynvim/_version.py
- pynvim/util.py
- setup.py
- test/test_version.py
pynvim previously did not have the `pynvim.__version__` attribute,
which is a popular convention for python modules.
We add the `pynvim.__version__` string in addition to `pynvim.VERSION`,
and let `pynvim._version` be the only file that contains the version
metadata for the pynvim package. `setup.py` can also get the version
string from this file.
pynvim version is bumped up to 0.5.0.dev0 (from 0.4.3).
> packaging: add pynvim.__version__ attribute (0.5.0.dev0)

- test/conftest.py
- test/test_vim.py
Problem:
The embedded neovim fixture instance for testing picks up `python3`
on the `$PATH`. This can be different from the current python.
(Example)
$ which python3
/usr/local/bin/python3
$ which python3.11
$HOME/.pyenvs/versions/3.11.5/bin/python3.11
$ python3.11 -m pytest
then neovim will have `/usr/local/bin/python3` as the python3 host,
so the behavior of `:python` (and `pynvim` especially when it has local
changes during development) can be different.
Solution:
The embedded nvim instance should always pin `g:python3_host_prog` to
`sys.executable`.
> test: always use the same exact python executable regardless of $PATH

- scripts/disable_log_statements.sh
- scripts/enable_log_statements.sh
- scripts/logging_statement_modifier.py
- `find -name` => `find . -name`
- `xargs -i` => `xargs -I` (or can be replaced by the for loop)
- Use bash for loop instead of xargs to abort early when erorr happens
- Have one whitespace after `#` in the comments to conform with the
standard python code style
(should the commit message be prefixed with `packaging:` or `fix:` ?)
> fix: invalid CLI use in scripts/{enable,disable}_log_statements.sh

- pynvim/msgpack_rpc/session.py
- pynvim/plugin/script_host.py
- test/test_vim.py
The Ex command `:py`, `:python`, :`py3`, etc. can evaluate the line as an expression rather than a statement if the line starts with `=`, just like `:lua=`.
`:py= <expr>` is equivalent as `:py print(<expr>)`.
```vim
:py3= sys.version_info[:3]
:python3 =pynvim.__version__
```
- How to document into `/doc/if_pyth.txt` (neovim core)? The feature would require pynvim 0.5.0 (or devel). It would make sense to submit a PR to neovim core only after a stable release of pynvim that contains this patch is released.
~~should be merged (or rebased) after #547 to avoid conflicts~~ (Merged)
> feat: Ex command `:py=` evaluate and print python expression 

- pynvim/_version.py
Breaking: Python 3.7 is the minimum supported Python version.
Changes since 0.4.3:
- 1696737 feat: Ex command ":py=" evaluate and print expression
- 86cc50e test: always use the same python regardless of $PATH
- 71d2d65 packaging: Add pynvim.__version__ attribute
- 056f6f9 fix: ignore flaky OSError on windows
- 6ab90aa fix: EOF error on piped stderr being closed on Windows
- fd4247c fix: do not leak resources across tests so as to prevent side effects
- 260a0b9 deps: Require greenlet >= 3.0 since it supports Python 3.12
- f244597 fix: broken dynamic import of rplugin modules
- e4224fc fix: sphinx "invalid language code"
- 61bf6fa fix: mypy type annotation warnings
- 5e84c75 fix: sphinx "Unexpected indentation" warning
- 991c689 fix: PEP 484 prohibits implicit Optional
- 919217d fix: …
> Pynvim 0.5.0

- .readthedocs.yml
This *might* fix the failing readthedocs CI #552 issue (can't fully test until merged).
> ci: fix failing readthedocs build by adding sphinx_rtd_theme dependency

- pynvim/api/buffer.py
- pynvim/api/common.py
- pynvim/api/nvim.py
- pynvim/api/tabpage.py
- pynvim/api/window.py
- pynvim/msgpack_rpc/event_loop/asyncio.py
With PEP-563 (Postponed evaluation of annotations), we can have a more
clean syntax of writing type hints, not using 'forward references' to
names that have not been defined yet in the form of string literals.
Note that Python 3.7+ (the minimum python version that is currently
supported by pynvim) supports PEP-563.
> refactor: remove the use of forward references

- test/test_vim.py
Problem:
Tests fail since upstream Nvim commit https://github.com/neovim/neovim/commit/eb5d15e3838f53e2fcd25989c88db87458e9f984 which removed the (internal) `provider#python3#Prog` function.
pynvim.api.common.NvimError: nvim_exec2(): Vim(echomsg):E117: Unknown function: provider#python3#Prog
Solution:
Use the new Lua function instead.
> fix(tests): tests

- README.md
- pynvim/plugin/script_host.py
- test/test_host.py
This reverts commit d549371b6fb647304cff5f88a71e2bc42d2ed30a. This fixes #523 and make UltiSnips usable. As mentioned by @jsr-p, the extra check is redundant and is not worth the slower performance.
> Revert "fix: vim.eval('v:true') should return python bool #506"

- pynvim/plugin/host.py
Specs were being found with a normalized path, but being requested without normalization. We now normalize the path we responding to spec requests.
fixes #564
> fix: UpdateRemotePlugins not finding specs on windows

- test/test_events.py
since Nvim 0.11 https://github.com/neovim/neovim/pull/28487 :
- nvim_subscribe, nvim_unsubscribe are deprecated
- rpcnotify(0) actually broadcasts instead of multicasts, thus nvim_subscribe/nvim_unsubscribe has no effect.
> fix(tests): broadcast test fails

- pynvim/plugin/script_host.py
python-neovim fails to build with Python 3.13.0b1.
According to https://docs.python.org/3.13/whatsnew/3.13.html:
logging: Remove undocumented and untested Logger.warn() and LoggerAdapter.warn() methods and logging.warn() function.  Deprecated since Python 3.3, they were aliases to the logging.Logger.warning() method, logging.LoggerAdapter.warning() method and logging.warning() function.
> fix: Remove deprecated alias of logger.warn

- setup.py
This does not seem to be used any longer.
Closes #572.
> fix(tests): remove reference to pytest-runner

- README.md
- docs/development.rst
- test/conftest.py
> docs: avoid deprecated $NVIM_LISTEN_ADDRESS env var

- test/test_vim.py
Fixes #571.
Problem: The `test_python3_ex_eval` test fails on python3.13 because the
format of stacktrace message has changed.
Solution: Check for important lines only.
> fix(tests): failing tests on python3.13 about stacktrace messages

- pynvim/_version.py
Changes since 0.5.0:
- 4813ce6 fix(tests): failing tests on python3.13 about stacktrace messages #578
- 9391eff docs: avoid deprecated $NVIM_LISTEN_ADDRESS env var #575
- 9fc77f0 fix(tests): remove reference to pytest-runner #573
- a855fa3 fix: deprecated alias of logger.warn #569
- cc45f5b fix(tests): broadcast test fails #570
- 4d65226 fix(ci): macOS CI fails with "Unrecognized archive format"
- d6dc8cf fix: UpdateRemotePlugins not finding specs on Windows #565
- 9f3e010 Revert "fix: vim.eval('v:true') should return python bool" #562
- f9d839f fix(tests): "provider#python3#Prog" was removed upstream #563
- 5f989df refactor: remove the use of forward references #558
- c4197f1 fix(ci): failing readthedocs build #554
- da0970e ci: fix failing readthedocs build
- 7a84048 fix(ci): failing …
> Pynvim 0.5.1

- .github/workflows/test.yml
macos-latest now points to M1 runners (macos-14-arm64) which do not support python 3.7-3.9. For these versions, use macos-12 runner.
Note: please do not squash commits for this PR.
> fix(ci): macOS CI failing with python{3.7, 3.8, 3.9}

- setup.py
Fix conditional `install_requires` in `setup.py` to use environment markers instead of inline conditions.  The latter do not work correctly with universal wheels -- e.g. a wheel made on Python 3.12 would not have a dependency on `typing-extensions` at all, even if it were installed on Python 3.11 or older, and the other way around.
> build: fix conditional `install_requires`

- pynvim/api/common.py
- pynvim/api/nvim.py
- pynvim/plugin/host.py
I noticed that it takes pynvim about 4ms to attach to an nvim instance for me, and 3ms of that is due to the single line:
metadata = walk(decode_if_bytes, metadata)
This commit reduces the walk() time down to 1.5ms, which brings the total attach time down to 2.5ms. This is helpful for me because in my use case I end up connecting to all of the currently-running nvim processes and this starts to take a noticeable amount of time. Unfortunately parallelization does not help here due to the nature of the slowness.
walk() is expensive because it does a very large amount of pure-python manipulation, so this commit is just some tweaks to reduce the overheads:
- *args and **kw make the function call slow, and we can avoid needing them by pre-packing the args into fn via functools.partial
- The …
> Microoptimize the walk() function

- pynvim/msgpack_rpc/event_loop/asyncio.py
Use PidfdChildWatcher if os.pidfd_open is available and works, and otherwise use ThreadedChildWatcher which should work in any case.
Fixes #583
> fix: remove the use of asyncio.get_child_watcher() for python3.14

- .github/workflows/test.yml
see https://github.com/neovim/neovim/pull/32194
> ci: neovim nightly name was changed

- pynvim/msgpack_rpc/event_loop/asyncio.py
- pynvim/msgpack_rpc/event_loop/base.py
Problem: When the remote Nvim instance is aborted or terminates, the pynvim client will face an exception `OSError: EOF`. It is not very clear what is wrong and why EOF is received.
Solution: This happens when the remote the nvim process terminates unexpectedly (or a tcp/file socket is broken or gets disconnected). We can provide a bit more detailed information about why the asyncio session is stopping, through asyncio Protocol. An `EOFError` will be raised instead of OSError.
For example, during pynvim's unit tests we may see:
```
EOFError: process_exited: pid = 40000, return_code = -6
```
which means that the Nvim subprocess (pid = 40000) exited unexpectedly after getting SIGABRT (signal 6), i.e. assertion failure. Other error messages such as SIGSEGV (signal 11) or connection lost …
> fix: improve EOFError exception when remote nvim crashes

- test/test_attach.py
"python" is the name for Python 2's interpreter. Since pynvim is now
Python 3 only, there's no reason to expect the legacy interpreter to be
available.
> fix(test_connect_stdio): invoke python3 instead of python

- README.md
- docs/installation.rst
- pynvim/python.py
- setup.py
- test/test_window.py
Problem: Detection of the pynvim module is currently done by finding the first Python interpreter in the `PATH` and checking if it can import pynvim.  This has several effects:
- Activation of an unrelated Python virtual environment will break automatic detection, unless pynvim is also installed in that environment.
- Installing pynvim to the expected location is difficult. User installation into the system-wide or user-wide Python site area is now deprecated.  On Ubuntu 24.04 with Python 3.12, for example, the command `pip install --user pynvim` now fails with the error message `error: externally-managed-environment`.
- Users may create a dedicated virtual environment in which to install pynvim, but Neovim won't detect it; instead, they must either activate it before launching Neovim …
> feat: Nvim can detect venv python via "pynvim-python" tool

- pynvim/python.py
Problem: python interpreter exit status is ignored by pynvim-python.
For example:
```console
$ pynvim-python -c 'import sys; sys.exit(5)'; echo $?
0
```
Solution: propagate the exit status from pynvim-python.
Use `sys.exit()` to return the interpreter's exit status as found in `subprocess.run().returncode`:
```console
$ pynvim-python -c 'import sys; sys.exit(5)'; echo $?
5
```
Despite the number of times I read over this code, I'm sorry to say I failed to notice the expected `sys.exit()` was missing.  This week, I woke from a sound sleep in the middle of the night with the thought that I didn't remember seeing `sys.exit()`; I got up to check, and sure enough I'd left it off.
> fix: return python interpreter exit status from pynvim-python
